# Generated by Django - COPY THIS TO YOUR MIGRATIONS FOLDER
# Save as: bashvilleapi/migrations/0008_note_blocks_migration.py

from django.db import migrations, models
import json


def migrate_content_to_blocks(apps, schema_editor):
    """
    Migrate existing content field to blocks structure.
    This preserves all existing note content by converting it to text blocks.
    """
    Note = apps.get_model("bashvilleapi", "Note")

    migrated_count = 0

    for note in Note.objects.all():
        # Only migrate if blocks is empty/missing and we have content
        if hasattr(note, "content") and getattr(note, "content", None):
            if not getattr(note, "blocks", None):
                # Convert content to a single text block
                note.blocks = [
                    {
                        "id": "block-1",
                        "type": "text",
                        "content": note.content,
                        "order": 0,
                    }
                ]
                note.save(update_fields=["blocks"])
                migrated_count += 1

    print(f"Migrated {migrated_count} notes from content to blocks format")


def reverse_blocks_to_content(apps, schema_editor):
    """
    Reverse migration - convert blocks back to content field.
    This is for rollback purposes only.
    """
    Note = apps.get_model("bashvilleapi", "Note")

    for note in Note.objects.all():
        if note.blocks:
            # Reconstruct content from blocks
            content_parts = []

            for block in note.blocks:
                if block.get("type") == "text":
                    content_parts.append(block.get("content", ""))
                elif block.get("type") == "checklist":
                    for item in block.get("items", []):
                        status = "[x]" if item.get("completed") else "[ ]"
                        content_parts.append(f"- {status} {item.get('text', '')}")
                elif block.get("type") == "code":
                    lang = block.get("language", "")
                    content_parts.append(f"```{lang}\n{block.get('content', '')}\n```")

            # Save reconstructed content (assuming content field still exists)
            reconstructed_content = "\n\n".join(content_parts)
            if hasattr(note, "content"):
                note.content = reconstructed_content
                note.save(update_fields=["content"])


class Migration(migrations.Migration):

    dependencies = [
        ("bashvilleapi", "0007_note_priority_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="blocks",
            field=models.JSONField(
                default=list, help_text="Content blocks (text, checklist, code, etc.)"
            ),
        ),
        migrations.RunPython(
            migrate_content_to_blocks,
            reverse_code=reverse_blocks_to_content,
        ),
    ]


"""
INSTRUCTIONS FOR APPLYING THIS MIGRATION:

1. Save this file as: bashvilleapi/migrations/0008_note_blocks_migration.py

2. Run the migration:
   python manage.py migrate bashvilleapi

3. Verify the migration worked:
   python manage.py shell
   >>> from bashvilleapi.models import Note
   >>> note = Note.objects.first()
   >>> print(note.blocks)  # Should show block structure
   >>> print(note.content)  # Should still work (computed from blocks)

4. OPTIONAL - Remove old content field:
   After confirming everything works, you can create another migration
   to remove the old content field from the database:
   
   python manage.py makemigrations bashvilleapi --name remove_content_field
   
   Then edit that migration to:
   operations = [
       migrations.RemoveField(
           model_name='note',
           name='content',
       ),
   ]

5. Test your API endpoints to ensure they work with the new block structure.
"""
