# Generated by Django 5.2.5 on 2025-08-19 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('primary_hex', models.CharField(max_length=7)),
                ('secondary_hex', models.CharField(max_length=7)),
                ('accent_hex', models.CharField(max_length=7)),
                ('background_hex', models.CharField(max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('command_text', models.TextField()),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order_index', 'label'],
                'unique_together': {('user', 'label')},
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('color_palette', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='bashvilleapi.colorpalette')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bashvilleapi.command')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bashvilleapi.project')),
            ],
            options={
                'unique_together': {('project', 'command')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='commands',
            field=models.ManyToManyField(blank=True, related_name='projects', through='bashvilleapi.ProjectCommand', to='bashvilleapi.command'),
        ),
    ]
