# Generated by Django 5.2.5 on 2025-08-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bashvilleapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='backend_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
