# Generated by Django 5.2.5 on 2025-08-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bashvilleapi', '0002_project_backend_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('static-tailwind', 'Static React + Tailwind'), ('static-css', 'Static React + Custom CSS'), ('fullstack-tailwind', 'Full-Stack (React + Django) + Tailwind'), ('fullstack-css', 'Full-Stack (React + Django) + Custom CSS')], default='static-tailwind', max_length=20),
        ),
    ]
