# Generated by Django 5.2.5 on 2025-09-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bashvilleapi', '0003_project_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorpalette',
            name='ui_hex',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
