# Generated by Django 5.2.5 on 2025-09-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bashvilleapi', '0004_add_ui_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorpalette',
            name='style_preferences',
            field=models.JSONField(default=dict, help_text='Advanced styling options: gradients, component overrides, layout preferences'),
        ),
    ]
