// src/utils/generateReadme.js

export const generateReadme = (project) => {
  const commands = project.commands_preview || [];
  const palette = project.color_palette_preview;

  let readme = `# ${project.title}\n\n`;

  // Add description
  if (project.description) {
    readme += `${project.description}\n\n`;
  }

  // Add color palette section
  if (palette) {
    readme += `## 🎨 Color Palette: ${palette.name}\n\n`;
    readme += `| Color | Hex Code | Preview |\n`;
    readme += `|-------|----------|----------|\n`;
    readme += `| Primary | \`${
      palette.primary_hex
    }\` | ![](https://via.placeholder.com/20x20/${palette.primary_hex.slice(1)}/000000?text=+) |\n`;
    readme += `| Secondary | \`${
      palette.secondary_hex
    }\` | ![](https://via.placeholder.com/20x20/${palette.secondary_hex.slice(1)}/000000?text=+) |\n`;
    readme += `| Accent | \`${
      palette.accent_hex
    }\` | ![](https://via.placeholder.com/20x20/${palette.accent_hex.slice(1)}/000000?text=+) |\n`;
    readme += `| Background | \`${
      palette.background_hex
    }\` | ![](https://via.placeholder.com/20x20/${palette.background_hex.slice(1)}/000000?text=+) |\n\n`;

    // Add CSS variables section
    readme += `### CSS Variables\n\n\`\`\`css\n`;
    readme += `:root {\n`;
    readme += `  --primary-color: ${palette.primary_hex};\n`;
    readme += `  --secondary-color: ${palette.secondary_hex};\n`;
    readme += `  --accent-color: ${palette.accent_hex};\n`;
    readme += `  --background-color: ${palette.background_hex};\n`;
    readme += `}\n\`\`\`\n\n`;
  }

  // Add setup section
  readme += `## 🚀 Quick Setup\n\n`;
  readme += `Run the setup script:\n\n`;
  readme += `\`\`\`bash\n`;
  readme += `chmod +x setup.sh\n`;
  readme += `./setup.sh\n`;
  readme += `\`\`\`\n\n`;

  // Add commands section
  if (commands.length > 0) {
    readme += `## 📋 Commands\n\n`;
    commands.forEach((cmd, index) => {
      readme += `### ${index + 1}. ${cmd.label}\n\n`;
      readme += `\`\`\`bash\n${cmd.command_text}\n\`\`\`\n\n`;
    });
  }

  // Add footer
  readme += `---\n\n`;
  readme += `*Generated by Bash Stash on ${new Date().toLocaleDateString()}*\n`;

  return readme;
};
